### PR TITLE
Replace vulnerabilities packages

### PR DESCRIPTION
**Pull request by DrNixx**
gulp-utils are depricated
Fix the ecosystem with recommended packages https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### CODE REVIEW

**Comment by waynebloss** [comment]
I don't use this package anymore. How would you like to own it?

**Comment by DrNixx** [comment]
I use gulp-nunjucks-api in some of my projects. If you give me write access, I could support this further.

**Comment by waynebloss** [comment]
I sent invites for github and npm collaborator.

**Comment by DrNixx** [comment]
Thnx!

**Pull request merged**
